{
 "title": "SysEleven - Quotas",
 "description": "Dashboard for SysEleven Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "project",
    "label": "Project",
    "query": {
     "query": "label_values(syseleven_compute_cores_total,project)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "SysEleven - Compute Cores",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "SysEleven - Compute Cores",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((max(syseleven_compute_cores_used{project=~\"$project\"})by(__name__, project, region) / max(syseleven_compute_cores_total{project=~\"$project\"})by(__name__, project, region)) * 100) by(region, project)",
       "legendFormat": "{{region}}"
      }
     ]
    },
    {
     "title": "SysEleven - Used Compute Cores",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "CPUs" } },
     "targets": [
      {
       "expr": "sum(max(syseleven_compute_cores_used{project=~\"$project\"})by(__name__, project, region)) by(region, project) ",
       "legendFormat": "{{region}} "
      }
     ]
    },
    {
     "title": "SysEleven - Total Compute Cores",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "CPUs" } },
     "targets": [
      {
       "expr": "sum(max(syseleven_compute_cores_total{project=~\"$project\"})by(__name__, project, region)) by(region, project) ",
       "legendFormat": "{{region}} "
      }
     ]
    }
   ]
  },
  {
   "title": "SysEleven - Compute Ram",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "SysEleven - Compute Ram",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((max(syseleven_compute_ram_used_megabytes{project=~\"$project\"})by(__name__, project, region) / max(syseleven_compute_ram_total_megabytes{project=~\"$project\"})by(__name__, project, region)) * 100) by(region, project)",
       "legendFormat": "{{region}}"
      }
     ]
    },
    {
     "title": "SysEleven - Used Compute Ram",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "sum(max(syseleven_compute_ram_used_megabytes{project=~\"$project\"})by(__name__, project, region)) by(region, project) ",
       "legendFormat": "{{region}} "
      }
     ]
    },
    {
     "title": "SysEleven - Total Compute Ram",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "sum(max(syseleven_compute_ram_total_megabytes{project=~\"$project\"})by(__name__, project, region)) by(region, project) ",
       "legendFormat": "{{region}} "
      }
     ]
    }
   ]
  },
  {
   "title": "SysEleven - S3 Space",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "SysEleven - S3 Space",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((max(syseleven_s3_space_used_bytes{project=~\"$project\"})by(__name__, project, region, type) / max(syseleven_s3_space_total_bytes{project=~\"$project\"})by(__name__, project, region, type)) * 100) by(region, project, type)",
       "legendFormat": "{{region}} - {{type}}"
      }
     ]
    },
    {
     "title": "SysEleven - Used S3 Space",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(max(syseleven_s3_space_used_bytes{project=~\"$project\"})by(__name__, project, region, type)) by(region, project, type) ",
       "legendFormat": "{{region}} - {{type}} "
      }
     ]
    },
    {
     "title": "SysEleven - Total S3 Space",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(max(syseleven_s3_space_total_bytes{project=~\"$project\"})by(__name__, project, region, type)) by(region, project, type) ",
       "legendFormat": "{{region}} - {{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SysEleven - Volume Space",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "SysEleven - Volume Space",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((max(syseleven_volume_space_used_gigabytes{project=~\"$project\"})by(__name__, project, region) / max(syseleven_volume_space_total_gigabytes{project=~\"$project\"})by(__name__, project, region)) * 100) by(region, project)",
       "legendFormat": "{{region}}"
      }
     ]
    },
    {
     "title": "SysEleven - Used Volume Space",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(max(syseleven_volume_space_used_gigabytes{project=~\"$project\"})by(__name__, project, region)) by(region, project) ",
       "legendFormat": "{{region}} "
      }
     ]
    },
    {
     "title": "SysEleven - Total Volume Space",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(max(syseleven_volume_space_total_gigabytes{project=~\"$project\"})by(__name__, project, region)) by(region, project) ",
       "legendFormat": "{{region}} "
      }
     ]
    }
   ]
  },
  {
   "title": "SysEleven - Volume Volumes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "SysEleven - Volume Volumes",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((max(syseleven_volume_volumes_used{project=~\"$project\"})by(__name__, project, region) / max(syseleven_volume_volumes_total{project=~\"$project\"})by(__name__, project, region)) * 100) by(region, project)",
       "legendFormat": "{{region}}"
      }
     ]
    },
    {
     "title": "SysEleven - Used Volumes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(max(syseleven_volume_volumes_used{project=~\"$project\"})by(__name__, project, region)) by(region, project) ",
       "legendFormat": "{{region}} "
      }
     ]
    },
    {
     "title": "SysEleven - Total Volumes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(max(syseleven_volume_volumes_total{project=~\"$project\"})by(__name__, project, region)) by(region, project) ",
       "legendFormat": "{{region}} "
      }
     ]
    }
   ]
  },
  {
   "title": "SysEleven - Compute Instances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "SysEleven - Compute Instances",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((max(syseleven_compute_instances_used{project=~\"$project\"})by(__name__, project, region) / max(syseleven_compute_instances_total{project=~\"$project\"})by(__name__, project, region)) * 100) by(region, project)",
       "legendFormat": "{{region}}"
      }
     ]
    },
    {
     "title": "SysEleven - Used Compute Instances",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "Instances" } },
     "targets": [
      {
       "expr": "sum(max(syseleven_compute_instances_used{project=~\"$project\"})by(__name__, project, region)) by(region, project) ",
       "legendFormat": "{{region}} "
      }
     ]
    },
    {
     "title": "SysEleven - Total Compute Instances",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "Instances" } },
     "targets": [
      {
       "expr": "sum(max(syseleven_compute_instances_total{project=~\"$project\"})by(__name__, project, region)) by(region, project) ",
       "legendFormat": "{{region}} "
      }
     ]
    }
   ]
  },
  {
   "title": "SysEleven - Network LoadBalancers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "SysEleven - Network LoadBalancers",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((max(syseleven_network_loadbalancers_used{project=~\"$project\"})by(__name__, project, region) / max(syseleven_network_loadbalancers_total{project=~\"$project\"})by(__name__, project, region)) * 100) by(region, project)",
       "legendFormat": "{{region}}"
      }
     ]
    },
    {
     "title": "SysEleven - Used Network LoadBalancers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(max(syseleven_network_loadbalancers_used{project=~\"$project\"})by(__name__, project, region)) by(region, project) ",
       "legendFormat": "{{region}} "
      }
     ]
    },
    {
     "title": "SysEleven - Total Network LoadBalancers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(max(syseleven_network_loadbalancers_total{project=~\"$project\"})by(__name__, project, region)) by(region, project) ",
       "legendFormat": "{{region}} "
      }
     ]
    }
   ]
  },
  {
   "title": "SysEleven - Network Floating IPs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "SysEleven - Network Floating IPs",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((max(syseleven_network_floating_ips_used{project=~\"$project\"})by(__name__, project, region) / max(syseleven_network_floating_ips_total{project=~\"$project\"})by(__name__, project, region)) * 100) by(region, project)",
       "legendFormat": "{{region}}"
      }
     ]
    },
    {
     "title": "SysEleven - Used Network Floating IPs",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "IPs" } },
     "targets": [
      {
       "expr": "sum(max(syseleven_network_floating_ips_used{project=~\"$project\"})by(__name__, project, region)) by(region, project) ",
       "legendFormat": "{{region}} "
      }
     ]
    },
    {
     "title": "SysEleven - Total Network Floating IPs",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "IPs" } },
     "targets": [
      {
       "expr": "sum(max(syseleven_network_floating_ips_total{project=~\"$project\"})by(__name__, project, region)) by(region, project) ",
       "legendFormat": "{{region}} "
      }
     ]
    }
   ]
  },
  {
   "title": "SysEleven - DNS Zones",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "SysEleven - DNS Zones",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((max(syseleven_dns_zones_used{project=~\"$project\"})by(__name__, project, region) / max(syseleven_dns_zones_total)by(__name__, project, region)) * 100) by(region, project)",
       "legendFormat": "{{region}}"
      }
     ]
    },
    {
     "title": "SysEleven - Used DNS Zones",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "Zones" } },
     "targets": [
      {
       "expr": "sum(max(syseleven_dns_zones_used{project=~\"$project\"})by(__name__, project, region)) by(region, project) ",
       "legendFormat": "{{region}} "
      }
     ]
    },
    {
     "title": "SysEleven - Total DNS Zones",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "Zones" } },
     "targets": [
      {
       "expr": "sum(max(syseleven_dns_zones_total{project=~\"$project\"})by(__name__, project, region)) by(region, project) ",
       "legendFormat": "{{region}} "
      }
     ]
    }
   ]
  }
 ]
}