{{- if and (or .Values.openstack.username .Values.openstack.password) (or .Values.openstack.application_credential_id .Values.openstack.application_credential_secret) }}
{{- fail "openstack.username/password and openstack.application_credential_id/application_credential_secret are mutually exclusive." }}
{{- end }}
{{- if not (or (and .Values.openstack.username .Values.openstack.password) (and .Values.openstack.application_credential_id .Values.openstack.application_credential_secret)) }}
{{- fail "One of openstack.username/password or openstack.application_credential_id/application_credential_secret is required." }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "syseleven-exporter.secret" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "syseleven-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- if .Values.openstack.username }}
  OS_USERNAME: {{ .Values.openstack.username }}
{{- end }}
{{- if .Values.openstack.password }}
  OS_PASSWORD: {{ .Values.openstack.password }}
{{- end }}
{{- if .Values.openstack.projectId }}
  OS_PROJECT_ID: {{ .Values.openstack.projectId }}
{{- end }}
{{- if .Values.openstack.application_credential_id }}
  OS_APPLICATION_CREDENTIAL_ID: {{ .Values.openstack.application_credential_id }}
{{- end }}
{{- if .Values.openstack.application_credential_secret }}
  OS_APPLICATION_CREDENTIAL_SECRET: {{ .Values.openstack.application_credential_secret }}
{{- end }}
