{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "syseleven-exporter.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "syseleven-exporter.labels" . | nindent 4 }}
  {{- if .Values.serviceAccount.labels }}
    {{- toYaml .Values.serviceAccount.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}
