apiVersion: v1
kind: Service
metadata:
  name: {{ include "syseleven-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "syseleven-exporter.labels" . | nindent 4 }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      name: {{ .Values.service.name }}
  selector:
    {{- include "syseleven-exporter.selectorLabels" . | nindent 4 }}
