name: Helm Chart Test

on:
  pull_request:
    paths:
      - "charts/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1

      - name: Install Helm Unittest Plugin
        run: |
          helm plugin install https://github.com/helm-unittest/helm-unittest.git --verify=false

      - name: Run Helm Unittests
        run: |
          helm unittest charts/syseleven-exporter-chart/
